services:
  - type: web
    name: sazeyar
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
