services:
  - type: web
    name: sazeyar
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.x
    staticPublishPath: ./dist
    autoDeploy: true
